#!/usr/bin/env node
/**
 * Generates all cryptographic material needed by AgentID:
 *   - RSA-2048 key pair  (JWT_PRIVATE_KEY, JWT_PUBLIC_KEY)  for RS256 signing
 *   - 32-byte HMAC secret (JWT_HMAC_SECRET) for pseudonymous sub derivation
 *
 * Run once: node scripts/generate-keys.mjs
 * Keys are written to (or appended to) .env.local.
 */

import { generateKeyPairSync, randomBytes } from 'crypto';
import { writeFileSync, existsSync, readFileSync } from 'fs';
import { join } from 'path';

const { privateKey, publicKey } = generateKeyPairSync('rsa', {
  modulusLength: 2048,
  publicKeyEncoding: { type: 'spki', format: 'pem' },
  privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
});

const hmacSecret = randomBytes(32).toString('hex');

// Escape newlines for single-line .env format
const privateKeyEnv = privateKey.replace(/\n/g, '\\n');
const publicKeyEnv = publicKey.replace(/\n/g, '\\n');

const keysBlock = `
# ── HMAC secret for pseudonymous sub — never share or commit this ───────────
# Changing this value resets all pseudonym linkages (useful for privacy resets)
JWT_HMAC_SECRET=${hmacSecret}

# ── JWT Signing Keys (generated by scripts/generate-keys.mjs) ──────────────
JWT_PRIVATE_KEY="${privateKeyEnv}"
JWT_PUBLIC_KEY="${publicKeyEnv}"
`;

const envPath = join(process.cwd(), '.env.local');

if (existsSync(envPath)) {
  const existing = readFileSync(envPath, 'utf-8');
  if (existing.includes('JWT_PRIVATE_KEY=')) {
    console.log('JWT keys already present in .env.local — skipping.');
    process.exit(0);
  }
  writeFileSync(envPath, existing + keysBlock);
  console.log('✓ JWT keys and HMAC secret appended to .env.local');
} else {
  const template = `# ── AgentID Environment Variables ─────────────────────────────────────────
# GrandID/E-identitet test environment
GRANDID_BASE_URL=https://client.test.grandid.com
GRANDID_API_KEY=your_api_key_here
GRANDID_SERVICE_KEY=your_service_key_here

# Public URL of this service (used to build authUrl returned to MCP clients)
NEXT_PUBLIC_APP_URL=http://localhost:3000
` + keysBlock;

  writeFileSync(envPath, template);
  console.log('✓ .env.local created with keys and placeholder GrandID credentials.');
  console.log('  Update GRANDID_API_KEY and GRANDID_SERVICE_KEY with your test credentials.');
}
